r2.0.7 : (log) fix -S problem, add `--tmp` ; (show) ban-list(soon) ; (issue) template

diff --git a/bin/log b/bin/log
--- a/bin/log
+++ b/bin/log
@@ -12,12 +12,16 @@ SUBPROG=$(echo $0 | awk -F'/' '{print $NF}')
 
 # ---[ Helps
 show_help() {
-    printf "%s\n" "Usage: $PROG $SUBPROG {-t|-s|-e|-u|-i|-S} <pattern>"
+    printf "%s\n" "Usage: $PROG $SUBPROG [OPTIONS] {-t|-s|-e|-u|-i|-S} <pattern>"
+    printf "%s\n" "       $PROG $SUBPROG [OPTIONS] <pattern>"
     printf "%s\n" "       $PROG $SUBPROG {-a,--all}"
-    printf "%s\n" "       $PROG $SUBPROG <pattern>"
+    printf "%s\n" "       $PROG $SUBPROG --tmp"
     echo ""
     format="%s\t%s\t%s\n"
     ( \
+    printf $format "OPTIONS" "" ""
+    printf $format "    --color={yes|no}" "highlight pattern or not" "[Default]: yes"
+    printf "\n"
     printf $format "-t,--time [TIME]" "list specific date log" "[TIME]={today,yesterday,3/3/2017,4/1}"
     printf $format "-s,--service [SERVICE]" "list specific service log" "[SERVICE]={sshd,hosts-monitor}"
     printf $format "-e,--event [EVENT]" "list specific event log" "[EVENT]={Invalid-User,Failed-Password,Manual}"
@@ -25,9 +29,9 @@ show_help() {
     printf $format "-i,--ip [IP]" "list specific login ip log" "[IP]=xxx.xxx.xxx.xxx"
     printf $format "-S,--status [STATUS]" "list specific ban/unban log" "[STATUS]={ban,unban}"
     printf $format "-a,--all" "list all log"
+    printf $format "--tmp" "show temp file (i.e.short-report)"
     printf $format "<pattern>" "search lines with the regex pattern" "ex: 'Ban', '^2018.*root', '\\(root\\|admin\\|user\\)'"
-    printf $format "--color={yes|no}" "highlight pattern or not" "[Default]: yes"
-    ) | column -t -s "$TAB" | awk '{print "   "$0}'
+    ) | column -e -t -s "$TAB" | awk '{print "   "$0}'
     echo ""
     echo "Example:"
     echo "   $PROG $SUBPROG -t yesterday -i 106.75.76.186"
@@ -35,11 +39,6 @@ show_help() {
 }
 
 # ---[ Contents
-if [ $# -eq 0 ]; then
-    print_header
-    cat ${report}* | grep --color=yes $(date -d today '+%F') | sort || sed 1d $shortrepo
-    exit 0
-fi
 while test $# -gt 0 ; do
     case $1 in
         "-h"|"--help"|"help")
@@ -72,7 +71,8 @@ while test $# -gt 0 ; do
             shift; shift;
             ;;
         "-S"|"--status")
-            echo $2 | grep "^[Bb][Aa][Nn]" > /dev/null && s="^Ban" || s=$2
+            s=$(echo $2 | sed 's/[bB][aA][nN]/Ban/g; s/[uU][nN][bB][aA][nN]/Unban/g') #grep "^[Bb][Aa][Nn]" > /dev/null && s="^Ban" || s=$2
+            echo "KEY: $s"
             STR="$STR $s"
             IDX="$IDX 7"
             shift; shift;
@@ -81,7 +81,12 @@ while test $# -gt 0 ; do
             STR="$(date '+%Y')"
             IDX="1"
             shift;
-            break;
+            ;;
+        "--tmp")
+            printf ">>> Show temp: $BOLD%s$RESET\n" "$shortrepo"
+            print_header
+            sed 1d $shortrepo
+            exit 0
             ;;
         --color|--color=*)
             if $(echo $1 | grep '=' > /dev/null) ; then 
@@ -99,27 +104,37 @@ while test $# -gt 0 ; do
             pattern=$1
             printf "Search pattern: $BOLD%s$RESET\n" "$pattern"
             shift;
-            case $1 in
-                --color|--color=*)
-                    if $(echo $1 | grep '=' > /dev/null) ; then 
-                        cop=$(echo $1 | awk -F'=' '{print $2}')
-                    else
-                        shift; cop=$1
-                    fi
-                    ;;
-                *)
-                    ;;
-            esac
-            print_header
-            cat ${report}* | grep --color=${cop:-yes} -i "$pattern" | sort || sed 1d $shortrepo
-            exit 0
+            #case $1 in
+                #--color|--color=*)
+                    #if $(echo $1 | grep '=' > /dev/null) ; then 
+                        #cop=$(echo $1 | awk -F'=' '{print $2}')
+                    #else
+                        #shift; cop=$1
+                    #fi
+                    #;;
+                #*)
+                    #;;
+            #esac
+            #print_header
+            #cat ${report}* | grep --color=${cop:-yes} -i "$pattern" | sort || sed 1d $shortrepo
+            #exit 0
             ;;
     esac
 done
+
 print_header
-awk -v "idxes=$IDX" -v "strs=$STR" \
-    'BEGIN{    split(idxes, idx, / +/);
-             n=split(strs, str, / +/); }
-    { flag=1; for (i=2;i<=n;i++) {
-        if (tolower($idx[i]) !~ tolower(str[i])) { flag=0; break; } }
-      if(flag) print $0 }' ${report}* | grep "\($(echo $STR | sed "s/ /\\\|/g;")\)" --color=${cop:-yes} | sort || sed 1d $shortrepo
+if [ -z "$STR" ] ; then
+    pattern=${pattern:-$(date -d today '+%F')}
+fi
+if [ -n "$pattern" ] ; then
+    # Serach pattern
+    cat ${report}* | grep --color=${cop:-yes} -i "$pattern" | sort
+    grep "$pattern" ${report}* > /dev/null || echo "(NOT FOUND)"
+else
+    awk -v "idxes=$IDX" -v "strs=$STR" \
+        'BEGIN{    split(idxes, idx, / +/);
+                 n=split(strs, str, / +/); }
+        { flag=1; for (i=2;i<=n;i++) {
+            if (tolower($idx[i]) !~ tolower(str[i])) { flag=0; break; } }
+          if(flag) print $0 }' ${report}* | grep "\($(echo $STR | sed "s/ /\\\|/g;")\)" --color=${cop:-yes} | sort
+fi
